<nav>

    <ul>
        <li>
            <img src="/images/logo.png" style="width:20%; padding: 1px; border-radius: 40px;"/>
            <a href="/">Java Forum Nord 2025</a>
        </li>
    </ul>

    <ul>
    </ul>
    <ul>
        <li><a href="/">Forms</a></li>
        <li><a href="/endless-scrolling?sort=name,desc">Endless Scrolling</a></li>
        <li><a href="/tables?sort=name,desc">Tables</a></li>
        <li><a href="/websockets">Websockets</a></li>
        <li><a href="modal-dialogs">Modal Dialogs</a></li>
        <li><a href="/llm-chat">LLM Chat</a></li>
    </ul>
</nav>